on: workflow_dispatch
jobs:
  Update-Dependencies:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./WebApplication1/WebApplication1
    steps:
      - name: dotnet outdated action
        uses: MCLD/dotnet-outdated-action@v4.1
        

